name: download artifact

on:
 workflow_dispatch
 
env:
 GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        run: |
          ls
          gh run download https://github.com/uddirulz/TestRun/actions/runs/5536589196 -n res.csv
          ls
          vi res.csv
