name: download artifact

on:
 workflow_dispatch
 
env:
 GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        run: |
          gh run download 5536589196 -n res.csv
          vi res.csv
