name: download artifact

on:
 workflow_dispatch
 
env:
 GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifact
        run: |
          ls
          gh run download 5536589196 -n my-artifact.zip
          ls
          vi res.csv
