name: pull

on:
 workflow_dispatch
 
jobs:
  container-test-job:
   runs-on: ubuntu-latest
   container:
    image: uddirulz/clockbox:latest
    options: --name=jmeter_cont
    credentials:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_TOKEN }}
     
   steps:
   - name: Print something
     id: setup
     run: |
      jmeter --version
      cd ${JMETER_HOME}
      ls
      pwd
      echo "date1=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT
   - name: Checkout
     uses: actions/checkout@v3
   - run: |
           ls
           printenv
           echo ${GITHUB_RUN_NUMBER}
   - name: Run JMTR Test
     run: jmeter.sh -n -t Dummy.jmx -l res.csv
   - name: Parse Junit XML
     run: python JunitParser.py
   - name: Junit
     id: junit_parser
     run: echo "count=$(grep -io "failure message" Test-Performance.xml | wc -l)" >> $GITHUB_OUTPUT
     
   - run: echo ${{steps.junit_parser.outputs.count}}
   
   - run: |
      apk add --no-cache py-pandas
      pip show pandas
   
   - run: pip3 install --no-cache-dir openpyxl==3.1.2
   
   - run: python csvImport.py
     
   - name: Validate JUNIT
     if: ${{ fromJSON(steps.junit_parser.outputs.count) != fromJSON(0) }}
     run: exit 1
   - uses: actions/upload-artifact@v3
     if: always()
     with:
      name: my-artifact
      path: |
       res.csv
       Test-Performance.xml
       Report Template.xlsx
       
     
