name: pull

on:
 workflow_dispatch
 
jobs:
  container-test-job:
   runs-on: ubuntu-latest
   container:
    image: uddirulz/clockbox:latest
    credentials:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_TOKEN }}
   steps:
   - name: Print something
     run: python 2+2
