name: pull

on:
 workflow_dispatch
 
jobs:
  container-test-job:
   runs-on: ubuntu-latest
   container:
    image: uddirulz/clockbox:latest
    credentials:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_TOKEN }}
   steps:
   - name: Print something
     run: |
      jmeter --version
      ls
      pwd
   - name: Checkout
     uses: actions/checkout@v3
   - run: |
           ls
           pwd
   - name: Run JMTR Test
     run: jmeter.sh -n -t Dummy.jmx -l TestRun/result.jtl

   - uses: actions/upload-artifact@v3
     with:
      name: my-artifact
      path: TestRun/result.jtl
   
     
