name: pull

on:
 workflow_dispatch
 
jobs:
  container-test-job:
   runs-on: ubuntu-latest
   container:
    image: uddirlz/clockbox:latest
    credentials:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_PASSWORD }}
   steps:
   - name: Print something
     run: echo "Testing flake8 job"
