name: pull

on:
 workflow_dispatch
 
jobs:
  container-test-job:
   runs-on: ubuntu-latest
   container:
    image: uddirulz/clockbox:latest
    credentials:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_TOKEN }}
   steps:
   - name: Print something
     run: |
      jmeter --version
      cd ${JMETER_HOME}
      ls
      pwd
   - name: Checkout
     uses: actions/checkout@v3
   - run: |
           ls
           printenv
   - name: Run JMTR Test
     run: jmeter.sh -n -t Dummy.jmx -l res.csv
   - name: Parse Junit XML
     id: junit_parser
     run: python JunitParser.py >> $GITHUB_OUTPUT
   - name: Validate JUNIT
     if: contains(${{steps.junit_parser.outputs.*}}, "Failure Message:")
     run: exit 1
   - uses: actions/upload-artifact@v3
     with:
      name: my-artifact
      path: res.csv
     
